name: Sonarqube Scan
agent:
    type: Unity::VM
    image: slough-ops/win10-base:stable
    flavor: b1.large
commands:
    - git submodule update --init --recursive
    - python3 -m pip install unity-downloader-cli --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade
    - unity-downloader-cli -u 2020.3.11f1 -c Editor
    - brew install mono corretto
    - curl https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/5.2.1.31210/sonar-scanner-msbuild-5.2.1.31210-net46.zip -o sonar-scanner-msbuild-net46.zip -L
    - unzip sonar-scanner-msbuild-net46.zip -d ~
    - chmod a+x ~/sonar-scanner-4.6.1.2450/bin/sonar-scanner
    - .Editor/Unity.app/Contents/MacOS/Unity -projectPath ./TestUrdfImporter -batchmode -quit -nographics -logFile - -executeMethod "UnityEditor.SyncVS.SyncSolution"
    - mono ~/SonarScanner.MSBuild.exe begin /k:"ai-robotics-urdf-importer" /d:sonar.host.url=$SONARQUBE_ENDPOINT_URL_STG /d:sonar.login=$SONARQUBE_TOKEN_STG /d:sonar.projectBaseDir=.
    - msbuild ./TestUrdfImporter/TestUrdfImporter.sln
    - mono ~/SonarScanner.MSBuild.exe end /d:sonar.login=$SONARQUBE_TOKEN_STG
triggers:
    cancel_old_ci: true
    expression: |
        ((pull_request.target eq "main" OR pull_request.target eq "dev")
        AND NOT pull_request.push.changes.all match "**/*.md") OR
        (push.branch eq "main" OR push.branch eq "dev")
