---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: unityCodeLinter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [master,dev]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: unityCodeLinter
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: false
          VALIDATE_XML: false
          VALIDATE_YAML: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: fasle
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
